name: "Push scaladoc on gh-pages"

on:
  push:
    branches:
      - dev
  release:
    types:
      - published

jobs:
  push-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/sbt
    - name: Build scaladoc
      run: sbt clean '++ 2.12.13' unidoc
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/scala-2.12/unidoc
        target-folder: ${{ github.ref_name }}
        single-commit: true
